import { Application } from '../models/index.js';

export const seedApplication = async () => {
  await Application.bulkCreate([
    {
      name: 'Frontend Developer at TechCorp',
      status: 'TODO',
      description: 'Apply for the frontend developer role focusing on React.js',
      company: 'TechCorp',
      position: 'Frontend Developer',
      saved: true,
      rejected: false,
      followup: false,
      interviews: false,
          },
    {
      name: 'Backend Engineer at CodeWorks',
      status: 'IN PROGRESS',
      description: 'Backend engineer position working with Node.js and PostgreSQL',
      company: 'CodeWorks',
      position: 'Backend Engineer',
      saved: true,
      rejected: false,
      followup: true,
      interviews: false,
          },
    {
      name: 'Full Stack Developer at DevStart',
      status: 'DONE',
      description: 'Completed application for a full stack role in a startup environment',
      company: 'DevStart',
      position: 'Full Stack Developer',
      saved: false,
      rejected: false,
      followup: false,
      interviews: true,
          },
    {
      name: 'Software Engineer at CloudSoft',
      status: 'TODO',
      description: 'Apply for a software engineering position with a cloud focus',
      company: 'CloudSoft',
      position: 'Software Engineer',
      saved: true,
      rejected: false,
      followup: false,
      interviews: false,
          },
    {
      name: 'Data Engineer at DataHive',
      status: 'IN PROGRESS',
      description: 'Big data and ETL pipeline development role',
      company: 'DataHive',
      position: 'Data Engineer',
      saved: true,
      rejected: false,
      followup: true,
      interviews: false,
          },
    {
      name: 'DevOps Engineer at InfraTech',
      status: 'DONE',
      description: 'Infrastructure automation and CI/CD role',
      company: 'InfraTech',
      position: 'DevOps Engineer',
      saved: false,
      rejected: false,
      followup: false,
      interviews: true,
          },
    {
      name: 'Mobile Developer at AppNation',
      status: 'TODO',
      description: 'Android/iOS mobile developer role focusing on React Native',
      company: 'AppNation',
      position: 'Mobile Developer',
      saved: true,
      rejected: false,
      followup: false,
      interviews: false,
          }
  ]);
};